spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:redis-test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: 127.0.0.1
      port: 6379